name: theta
description: Oppkey Dart interface for RICOH THETA 360 cameras
version: 0.3.1
homepage: https://oppkey.github.io/oppkey_theta_atk/

environment:
  sdk: '>=2.14.0 <3.0.0'


dependencies:
  dio: ^4.0.0
#   path: ^1.8.0
  http: ^0.13.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
