name: opptheta
publish_to: none
description: Command line tester for RICOH THETA 360 cameras by Oppkey
version: 0.3.1
homepage: https://oppkey.github.io/oppkey_theta_atk/

environment:
  sdk: '>=2.14.3 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  args: ^2.3.0
  theta:
    path: packages/theta