name: opptheta
publish_to: none
description: Oppkey API Test Kit for RICOH THETA
version: 0.2.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  args: ^2.3.0
  theta:
    path: packages/theta